<template>
	<div class="mealManagePage">
    <!----------------------公共头部------------------------->
    <common-header :headerTitle="headerTitle" :url="url">
      <!-------------添加公共头部添加菜品按钮----------------->
      <add-item :addLink="addLink"></add-item>
    </common-header>
    <!----------------------slideMenu----------------------->
    <slide-menu :slideList="mealTypeList"></slide-menu>
    <!-----------------------菜品列表------------------------>
    <meal-mange-list :mealTypeList="mealTypeList"></meal-mange-list>
  </div>
</template>

<script type="text/ecmascript-6">
  import $ from 'jquery';
  //引入公共组件
  import CommonHeader from '../components/common/CommonHeader';
  import AddItem from '../components/common/AddItem';
  import SlideMenu from '../components/common/SlideMenu';

  import MealMangeList from '../components/mealManage/MealTypeList';
	export default {
    data:function(){
      return{
        'headerTitle':'菜品管理',
        'url':'#/setting',
        'addLink':'#/addMeal',
        'mealTypeList':[
          {
            'type':'凉菜',
            'mealList':[
              {
                'mealId':'01',
                'imgUrl':'/static/images/meal/meal01.jpg',
                'mealTitle':'素拼',
                'mealCode':'s',
                'mealType':'凉菜',
                'mealPrice':10.00,
                'unit':'份',
                'show':true
              },
              {
                'mealId':'02',
                'imgUrl':'/static/images/meal/meal02.jpg',
                'mealTitle':'红油耳丝',
                'mealCode':'h',
                'mealType':'凉菜',
                'mealPrice':30.00,
                'unit':'份',
                'show':true
              },
              {
                'mealId':'03',
                'imgUrl':'/static/images/meal/meal03.jpg',
                'mealTitle':'蓑衣黄瓜',
                'mealCode':'s',
                'mealType':'凉菜',
                'mealPrice':10.00,
                'unit':'份',
                'show':false
              }
            ]
          },
          {
            'type':'热菜',
            'mealList':[
              {
                'mealId':'04',
                'imgUrl':'/static/images/meal/meal04.jpg',
                'mealTitle':'孜然羊肉',
                'mealCode':'z',
                'mealType':'热菜',
                'mealPrice':30.00,
                'unit':'份',
                'show':true
              },
              {
                'mealId':'05',
                'imgUrl':'/static/images/meal/meal05.jpg',
                'mealTitle':'宫保鸡丁',
                'mealCode':'g',
                'mealType':'热菜',
                'mealPrice':25.00,
                'unit':'份',
                'show':true
              },
              {
                'mealId':'06',
                'imgUrl':'/static/images/meal/meal06.jpg',
                'mealTitle':'小炒肉',
                'mealCode':'x',
                'mealType':'热菜',
                'mealPrice':25.00,
                'unit':'份',
                'show':true
              }
            ]
          },
          {
            'type':'干锅',
            'mealList':[
              {
                'mealId':'07',
                'imgUrl':'/static/images/meal/meal07.jpg',
                'mealTitle':'干锅肥肠',
                'mealCode':'f',
                'mealType':'干锅',
                'mealPrice':35.00,
                'unit':'份',
                'show':false
              },
              {
                'mealId':'08',
                'imgUrl':'/static/images/meal/meal08.jpg',
                'mealTitle':'干锅千页豆腐',
                'mealCode':'q',
                'mealType':'干锅',
                'mealPrice':25.00,
                'unit':'份',
                'show':false
              },
              {
                'mealId':'09',
                'imgUrl':'/static/images/meal/meal09.jpg',
                'mealTitle':'干锅土豆片',
                'mealCode':'t',
                'mealType':'干锅',
                'mealPrice':20.00,
                'unit':'份',
                'show':true
              }
            ]
          },
          {
            'type':'砂锅',
            'mealList':[
              {
                'url':'#/meal07',
                'imgUrl':'/static/images/meal/meal07.jpg',
                'mealTitle':'干锅肥肠',
                'mealPrice':35.00,
                'unit':'份',
                'show':false
              },
              {
                'url':'#/meal08',
                'imgUrl':'/static/images/meal/meal08.jpg',
                'mealTitle':'干锅千页豆腐',
                'mealPrice':25.00,
                'unit':'份',
                'show':false
              },
              {
                'url':'#/meal09',
                'imgUrl':'/static/images/meal/meal09.jpg',
                'mealTitle':'干锅土豆片',
                'mealPrice':20.00,
                'unit':'份',
                'show':true
              }
            ]
          },
          {
            'type':'青菜',
            'mealList':[
              {
                'url':'#/meal07',
                'imgUrl':'/static/images/meal/meal07.jpg',
                'mealTitle':'干锅肥肠',
                'mealPrice':35.00,
                'unit':'份',
                'show':false
              },
              {
                'url':'#/meal08',
                'imgUrl':'/static/images/meal/meal08.jpg',
                'mealTitle':'干锅千页豆腐',
                'mealPrice':25.00,
                'unit':'份',
                'show':false
              },
              {
                'url':'#/meal09',
                'imgUrl':'/static/images/meal/meal09.jpg',
                'mealTitle':'干锅土豆片',
                'mealPrice':20.00,
                'unit':'份',
                'show':true
              }
            ]
          },
          {
            'type':'炒饭',
            'mealList':[
              {
                'url':'#/meal07',
                'imgUrl':'/static/images/meal/meal07.jpg',
                'mealTitle':'干锅肥肠',
                'mealPrice':35.00,
                'unit':'份',
                'show':false
              },
              {
                'url':'#/meal08',
                'imgUrl':'/static/images/meal/meal08.jpg',
                'mealTitle':'干锅千页豆腐',
                'mealPrice':25.00,
                'unit':'份',
                'show':false
              },
              {
                'url':'#/meal09',
                'imgUrl':'/static/images/meal/meal09.jpg',
                'mealTitle':'干锅土豆片',
                'mealPrice':20.00,
                'unit':'份',
                'show':true
              }
            ]
          },
          {
            'type':'炒面',
            'mealList':[
              {
                'url':'#/meal07',
                'imgUrl':'/static/images/meal/meal07.jpg',
                'mealTitle':'干锅肥肠',
                'mealPrice':35.00,
                'unit':'份',
                'show':false
              },
              {
                'url':'#/meal08',
                'imgUrl':'/static/images/meal/meal08.jpg',
                'mealTitle':'干锅千页豆腐',
                'mealPrice':25.00,
                'unit':'份',
                'show':false
              },
              {
                'url':'#/meal09',
                'imgUrl':'/static/images/meal/meal09.jpg',
                'mealTitle':'干锅土豆片',
                'mealPrice':20.00,
                'unit':'份',
                'show':true
              }
            ]
          },
          {
            'type':'盖浇面',
            'mealList':[
              {
                'url':'#/meal07',
                'imgUrl':'/static/images/meal/meal07.jpg',
                'mealTitle':'干锅肥肠',
                'mealPrice':35.00,
                'unit':'份',
                'show':false
              },
              {
                'url':'#/meal08',
                'imgUrl':'/static/images/meal/meal08.jpg',
                'mealTitle':'干锅千页豆腐',
                'mealPrice':25.00,
                'unit':'份',
                'show':false
              },
              {
                'url':'#/meal09',
                'imgUrl':'/static/images/meal/meal09.jpg',
                'mealTitle':'干锅土豆片',
                'mealPrice':20.00,
                'unit':'份',
                'show':true
              }
            ]
          }
        ]
      }
    },
    components:{
      CommonHeader,
      AddItem,
      SlideMenu,
      MealMangeList
    },
    methods:{
    }
  }
</script>

<style scoped>
  /*-------------------圣杯布局--------------------*/
  .mealManagePage{
    height:100vh;
    overflow: hidden;
    display: flex;
    flex-direction: column;
    -webkit-flex-direction: column;
    justify-content: space-between;
    -webkit-justify-content: space-between;
  }
</style>
